## Model selection

### Three state-of-the-art algorithms
* Gradient Boosting Classifier
* Tensorflow Neural Network

In [1]:
import numpy as np
import pandas as pd
import random


from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import StratifiedKFold

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from keras_tuner import RandomSearch


#set random seed
my_seed=42
np.random.seed(my_seed)

#diable warning printing
import warnings
warnings.filterwarnings('ignore')

In [2]:
# Data set load
data=pd.read_csv('./data/C201905_counterfactuals/simulation_C201905_counterfactuals__ev0.1812.csv',index_col=0)


# Create a target variable, 'delay' and remove unnecessary columns
data['delay']=(data['actual_duration']>data['baseline_duration'])*1
data.drop(columns=['actual_duration','baseline_duration','critical_path'],inplace=True)
# Sort the columns
columns_sorted = sorted(data.columns, key=lambda x: int(x.replace('duration', '')) if 'duration' in x else float('inf'))
data = data[columns_sorted]
data.head(2)

,duration1,duration2,duration3,duration4,duration5,duration6,duration7,duration8,duration9,duration10,duration11,duration12,duration13,duration14,duration15,delay
0,1738.595774,1967.122966,256.504345,2186.408241,1723.181771,1898.648645,1795.289433,1599.760892,2224.382275,2489.048379,2124.279759,139.271436,8.498099,234.542254,7.655393,1
1,1717.864331,1881.352898,266.048082,2324.022291,1849.728508,2083.309016,1839.782891,1593.929687,2323.598219,2279.745524,2334.495021,145.448900,8.235859,238.908956,8.357302,1

In [3]:
# Normalize the dataset to improve the performance of the classifiers

def normalize_dataframe(df, feature_range=(0, 1)):
    """
    Normaliza un DataFrame de pandas utilizando MinMaxScaler.

    Args:
        df (pd.DataFrame): DataFrame a normalizar.
        feature_range (tuple): Rango de valores para la normalización (por defecto (0, 1)).

    Returns:
        pd.DataFrame: DataFrame normalizado.
        MinMaxScaler: Escalador utilizado para la normalización.
    """
    scaler = MinMaxScaler(feature_range=feature_range)
    normalized_data = scaler.fit_transform(df)
    normalized_df = pd.DataFrame(normalized_data, columns=df.columns, index=df.index)
    return normalized_df, scaler

def denormalize_dataframe(normalized_df, scaler):
    """
    Desnormaliza un DataFrame de pandas utilizando un MinMaxScaler previamente ajustado.

    Args:
        normalized_df (pd.DataFrame): DataFrame normalizado.
        scaler (MinMaxScaler): Escalador utilizado para la normalización.

    Returns:
        pd.DataFrame: DataFrame desnormalizado.
    """
    denormalized_data = scaler.inverse_transform(normalized_df)
    denormalized_df = pd.DataFrame(denormalized_data, columns=normalized_df.columns, index=normalized_df.index)
    return denormalized_df


data_to_normalize = data.iloc[:, :-1]  # Select all columns except the last one
normalized_data, my_scaler = normalize_dataframe(data_to_normalize)
data = pd.concat([normalized_data, data.iloc[:, -1]], axis=1)  # Combine normalized data with the last column

data.head(2)

,duration1,duration2,duration3,duration4,duration5,duration6,duration7,duration8,duration9,duration10,duration11,duration12,duration13,duration14,duration15,delay
0,0.751643,0.821171,0.653332,0.547362,0.393468,0.432562,0.715566,0.442461,0.804429,0.891496,0.551165,0.700622,0.641918,0.698465,0.380315,1
1,0.675055,0.594889,0.759338,0.713173,0.582989,0.679778,0.789338,0.432862,0.938094,0.637179,0.819892,0.830761,0.556337,0.752252,0.604439,1

In [4]:
# Split the dataset into features and class
X = data.drop(columns=['delay'])
y = data['delay']

# "stratify=y is used in train_test_split to ensure that the class distribution remains the same in both the training and test sets."
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=my_seed, stratify=y)

# Verify the split
print("Unique labels in training:", np.unique(y_train, return_counts=True))
print("Unique labels in test:", np.unique(y_test, return_counts=True))

Unique labels in training: (array([0, 1]), array([ 5564, 14436]))
Unique labels in test: (array([0, 1]), array([1391, 3609]))

### Gradient Boosting Clasifier

In [5]:
# Results dataframe
results = pd.DataFrame([],columns=['model','kf','Accuracy'])

# Stratified K-Fold cross-validation
kfold =StratifiedKFold(n_splits=5, random_state=my_seed,shuffle=True)

In [6]:
model='GradientBoostingC'
k=0
for train_index, test_index in kfold.split(X,y):

  # parameter optimization in the inner folds
    # n_estimators: number of  boosting stages
    # max_depth of the regression estimators
  mdc = GridSearchCV(GradientBoostingClassifier(),
                    param_grid={"n_estimators": np.linspace(50,200,10).astype('int'),  
                                "max_depth": np.linspace(1,10,5).astype('int')},
                    n_jobs=6)  
  mdc.fit(X.iloc[train_index,:], y.iloc[train_index])
  
  # score of the best model in the outer fold
  results = results._append( pd.DataFrame([[model,k, accuracy_score(y.iloc[test_index],mdc.best_estimator_.predict(X.iloc[test_index,:]))]],columns=['model','kf','Accuracy']))
  k+=1

### Tensorflow neural network

In [8]:
def build_model(hp):
    model = keras.Sequential([
        layers.Dense(hp.Int('units', min_value=32, max_value=128, step=32), activation='relu', kernel_regularizer=tf.keras.regularizers.l2(0.01)),
        layers.Dense(2, activation='softmax')
    ])
    model.compile(optimizer=keras.optimizers.Adam(hp.Choice('learning_rate', [0.01, 0.001, 0.0001])),
                  loss='sparse_categorical_crossentropy',
                  metrics=['accuracy'])
    return model

model='Tensorflow'
k=0
for train_index, test_index in kfold.split(X,y):

  # parameter optimization in the inner folds
    # units: number of  neurons in the hidden layer
    # learning_rate
  tuner = RandomSearch(build_model, objective='val_accuracy', max_trials=10, executions_per_trial=1, directory='tuner_dir')

  tuner.search(X.iloc[train_index,:], y.iloc[train_index], epochs=30, validation_split=0.2, batch_size=32) 
  best_hps = tuner.get_best_hyperparameters(num_trials=1)[0]
  best_model = tuner.hypermodel.build(best_hps)
  best_model.fit(X.iloc[train_index,:], y.iloc[train_index], epochs=30, batch_size=32, validation_split=0.2, callbacks=[tf.keras.callbacks.EarlyStopping(patience=5, restore_best_weights=True)])
  test_loss, test_acc = best_model.evaluate(X.iloc[test_index,:], y.iloc[test_index])
  
  # score of the best model in the outer fold
  results = results._append( pd.DataFrame([[model,k, test_acc]],columns=['model','kf','Accuracy']))
  k+=1

Reloading Tuner from tuner_dir/untitled_project/tuner0.json
Epoch 1/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 561us/step - accuracy: 0.7321 - loss: 0.6586 - val_accuracy: 0.8242 - val_loss: 0.4155
Epoch 2/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 438us/step - accuracy: 0.8490 - loss: 0.3973 - val_accuracy: 0.8540 - val_loss: 0.3633
Epoch 3/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 433us/step - accuracy: 0.8604 - loss: 0.3502 - val_accuracy: 0.8580 - val_loss: 0.3347
Epoch 4/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 428us/step - accuracy: 0.8593 - loss: 0.3400 - val_accuracy: 0.8562 - val_loss: 0.3227
Epoch 5/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 433us/step - accuracy: 0.8656 - loss: 0.3187 - val_accuracy: 0.8635 - val_loss: 0.3227
Epoch 6/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 430us/step - accuracy: 0.8682 - loss: 0.3163 - val_accuracy: 0.8590 - val_loss: 0.3100
Epoch 7/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 431us/step - accuracy: 0.8669 - loss: 0.3099 - val_accuracy: 0.8558 - val_loss: 0.3111
Epoch 8/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 454us/step - accuracy: 0.8697 - loss: 0.3027 - val_accuracy: 0.8655 - val_loss: 0.3240
Epoch 9/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 454us/step - accuracy: 0.8677 - loss: 0.2990 - val_accuracy: 0.8585 - val_loss: 0.3059
Epoch 10/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 443us/step - accuracy: 0.8672 - loss: 0.3017 - val_accuracy: 0.8630 - val_loss: 0.3004
Epoch 11/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 450us/step - accuracy: 0.8736 - loss: 0.2967 - val_accuracy: 0.8658 - val_loss: 0.2988
Epoch 12/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 432us/step - accuracy: 0.8700 - loss: 0.3003 - val_accuracy: 0.8683 - val_loss: 0.3044
Epoch 13/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 431us/step - accuracy: 0.8746 - loss: 0.2883 - val_accuracy: 0.8535 - val_loss: 0.3163
Epoch 14/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 455us/step - accuracy: 0.8761 - loss: 0.2888 - val_accuracy: 0.8788 - val_loss: 0.2850
Epoch 15/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 493us/step - accuracy: 0.8844 - loss: 0.2745 - val_accuracy: 0.8867 - val_loss: 0.2651
Epoch 16/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 430us/step - accuracy: 0.8952 - loss: 0.2640 - val_accuracy: 0.8960 - val_loss: 0.2498
Epoch 17/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 442us/step - accuracy: 0.9073 - loss: 0.2454 - val_accuracy: 0.9118 - val_loss: 0.2348
Epoch 18/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 445us/step - accuracy: 0.9140 - loss: 0.2331 - val_accuracy: 0.9195 - val_loss: 0.2523
Epoch 19/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 488us/step - accuracy: 0.9222 - loss: 0.2283 - val_accuracy: 0.9402 - val_loss: 0.2091
Epoch 20/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 456us/step - accuracy: 0.9362 - loss: 0.2063 - val_accuracy: 0.9467 - val_loss: 0.2037
Epoch 21/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 450us/step - accuracy: 0.9354 - loss: 0.2068 - val_accuracy: 0.9565 - val_loss: 0.1925
Epoch 22/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 439us/step - accuracy: 0.9502 - loss: 0.1920 - val_accuracy: 0.9578 - val_loss: 0.1818
Epoch 23/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 432us/step - accuracy: 0.9480 - loss: 0.1944 - val_accuracy: 0.9133 - val_loss: 0.2088
Epoch 24/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 439us/step - accuracy: 0.9539 - loss: 0.1809 - val_accuracy: 0.9685 - val_loss: 0.1698
Epoch 25/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 429us/step - accuracy: 0.9585 - loss: 0.1781 - val_accuracy: 0.9285 - val_loss: 0.1893
Epoch 26/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 432us/step - accuracy: 0.9580 - loss: 0.1747 - val_accuracy: 0.9657 - val_loss: 0.1749
Epoch 27/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 430us/step - accuracy: 0.9612 - loss: 0.1719 - val_accuracy: 0.9695 - val_loss: 0.1580
Epoch 28/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 431us/step - accuracy: 0.9637 - loss: 0.1640 - val_accuracy: 0.9758 - val_loss: 0.1585
Epoch 29/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 429us/step - accuracy: 0.9657 - loss: 0.1606 - val_accuracy: 0.9743 - val_loss: 0.1536
Epoch 30/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 442us/step - accuracy: 0.9659 - loss: 0.1566 - val_accuracy: 0.9778 - val_loss: 0.1499
157/157 ━━━━━━━━━━━━━━━━━━━━ 0s 356us/step - accuracy: 0.9689 - loss: 0.1538
Reloading Tuner from tuner_dir/untitled_project/tuner0.json
Epoch 1/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 547us/step - accuracy: 0.7313 - loss: 0.6610 - val_accuracy: 0.8213 - val_loss: 0.4193
Epoch 2/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 436us/step - accuracy: 0.8434 - loss: 0.3976 - val_accuracy: 0.8558 - val_loss: 0.3583
Epoch 3/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 481us/step - accuracy: 0.8564 - loss: 0.3523 - val_accuracy: 0.8375 - val_loss: 0.3508
Epoch 4/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 441us/step - accuracy: 0.8656 - loss: 0.3307 - val_accuracy: 0.8533 - val_loss: 0.3258
Epoch 5/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 459us/step - accuracy: 0.8641 - loss: 0.3216 - val_accuracy: 0.8655 - val_loss: 0.3353
Epoch 6/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 433us/step - accuracy: 0.8659 - loss: 0.3109 - val_accuracy: 0.8662 - val_loss: 0.3198
Epoch 7/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 431us/step - accuracy: 0.8704 - loss: 0.3047 - val_accuracy: 0.8648 - val_loss: 0.3005
Epoch 8/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 429us/step - accuracy: 0.8746 - loss: 0.2979 - val_accuracy: 0.8702 - val_loss: 0.2915
Epoch 9/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 431us/step - accuracy: 0.8791 - loss: 0.2873 - val_accuracy: 0.8698 - val_loss: 0.2947
Epoch 10/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 431us/step - accuracy: 0.8856 - loss: 0.2757 - val_accuracy: 0.8930 - val_loss: 0.2585
Epoch 11/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 427us/step - accuracy: 0.9006 - loss: 0.2577 - val_accuracy: 0.9135 - val_loss: 0.2358
Epoch 12/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 436us/step - accuracy: 0.9213 - loss: 0.2351 - val_accuracy: 0.9352 - val_loss: 0.2176
Epoch 13/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 427us/step - accuracy: 0.9333 - loss: 0.2186 - val_accuracy: 0.9460 - val_loss: 0.2117
Epoch 14/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 426us/step - accuracy: 0.9415 - loss: 0.2069 - val_accuracy: 0.9435 - val_loss: 0.1927
Epoch 15/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 462us/step - accuracy: 0.9489 - loss: 0.1937 - val_accuracy: 0.9610 - val_loss: 0.1783
Epoch 16/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 450us/step - accuracy: 0.9535 - loss: 0.1854 - val_accuracy: 0.9525 - val_loss: 0.1776
Epoch 17/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 428us/step - accuracy: 0.9583 - loss: 0.1789 - val_accuracy: 0.9617 - val_loss: 0.1801
Epoch 18/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 431us/step - accuracy: 0.9596 - loss: 0.1743 - val_accuracy: 0.9395 - val_loss: 0.1753
Epoch 19/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 440us/step - accuracy: 0.9675 - loss: 0.1636 - val_accuracy: 0.9753 - val_loss: 0.1557
Epoch 20/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 431us/step - accuracy: 0.9647 - loss: 0.1610 - val_accuracy: 0.9610 - val_loss: 0.1566
Epoch 21/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 429us/step - accuracy: 0.9660 - loss: 0.1556 - val_accuracy: 0.9793 - val_loss: 0.1467
Epoch 22/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 433us/step - accuracy: 0.9696 - loss: 0.1486 - val_accuracy: 0.9610 - val_loss: 0.1505
Epoch 23/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 493us/step - accuracy: 0.9677 - loss: 0.1511 - val_accuracy: 0.9660 - val_loss: 0.1523
Epoch 24/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 455us/step - accuracy: 0.9686 - loss: 0.1450 - val_accuracy: 0.9615 - val_loss: 0.1433
Epoch 25/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 477us/step - accuracy: 0.9652 - loss: 0.1483 - val_accuracy: 0.9765 - val_loss: 0.1353
Epoch 26/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 434us/step - accuracy: 0.9676 - loss: 0.1421 - val_accuracy: 0.9862 - val_loss: 0.1315
Epoch 27/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 447us/step - accuracy: 0.9717 - loss: 0.1372 - val_accuracy: 0.9818 - val_loss: 0.1301
Epoch 28/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 427us/step - accuracy: 0.9744 - loss: 0.1342 - val_accuracy: 0.9728 - val_loss: 0.1298
Epoch 29/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 430us/step - accuracy: 0.9667 - loss: 0.1401 - val_accuracy: 0.9640 - val_loss: 0.1421
Epoch 30/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 446us/step - accuracy: 0.9673 - loss: 0.1350 - val_accuracy: 0.9690 - val_loss: 0.1288
157/157 ━━━━━━━━━━━━━━━━━━━━ 0s 361us/step - accuracy: 0.9637 - loss: 0.1417
Reloading Tuner from tuner_dir/untitled_project/tuner0.json
Epoch 1/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 554us/step - accuracy: 0.7370 - loss: 0.6610 - val_accuracy: 0.8485 - val_loss: 0.4122
Epoch 2/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 431us/step - accuracy: 0.8381 - loss: 0.4013 - val_accuracy: 0.8453 - val_loss: 0.3602
Epoch 3/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 432us/step - accuracy: 0.8552 - loss: 0.3590 - val_accuracy: 0.8680 - val_loss: 0.3276
Epoch 4/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 430us/step - accuracy: 0.8605 - loss: 0.3317 - val_accuracy: 0.8565 - val_loss: 0.3205
Epoch 5/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 429us/step - accuracy: 0.8608 - loss: 0.3253 - val_accuracy: 0.8730 - val_loss: 0.3068
Epoch 6/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 429us/step - accuracy: 0.8706 - loss: 0.3078 - val_accuracy: 0.8555 - val_loss: 0.3208
Epoch 7/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 437us/step - accuracy: 0.8612 - loss: 0.3182 - val_accuracy: 0.8700 - val_loss: 0.2956
Epoch 8/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 429us/step - accuracy: 0.8598 - loss: 0.3150 - val_accuracy: 0.8700 - val_loss: 0.2945
Epoch 9/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 428us/step - accuracy: 0.8709 - loss: 0.2988 - val_accuracy: 0.8735 - val_loss: 0.2850
Epoch 10/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 428us/step - accuracy: 0.8811 - loss: 0.2863 - val_accuracy: 0.8945 - val_loss: 0.2655
Epoch 11/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 428us/step - accuracy: 0.8943 - loss: 0.2669 - val_accuracy: 0.9172 - val_loss: 0.2398
Epoch 12/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 479us/step - accuracy: 0.9120 - loss: 0.2447 - val_accuracy: 0.9402 - val_loss: 0.2217
Epoch 13/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 432us/step - accuracy: 0.9299 - loss: 0.2257 - val_accuracy: 0.9413 - val_loss: 0.2038
Epoch 14/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 438us/step - accuracy: 0.9427 - loss: 0.2060 - val_accuracy: 0.9408 - val_loss: 0.1964
Epoch 15/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 428us/step - accuracy: 0.9475 - loss: 0.2017 - val_accuracy: 0.9620 - val_loss: 0.1811
Epoch 16/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 428us/step - accuracy: 0.9556 - loss: 0.1869 - val_accuracy: 0.9695 - val_loss: 0.1711
Epoch 17/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 426us/step - accuracy: 0.9596 - loss: 0.1817 - val_accuracy: 0.9685 - val_loss: 0.1646
Epoch 18/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 429us/step - accuracy: 0.9571 - loss: 0.1770 - val_accuracy: 0.9710 - val_loss: 0.1588
Epoch 19/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 424us/step - accuracy: 0.9627 - loss: 0.1691 - val_accuracy: 0.9445 - val_loss: 0.1742
Epoch 20/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 462us/step - accuracy: 0.9607 - loss: 0.1681 - val_accuracy: 0.9087 - val_loss: 0.2201
Epoch 21/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 438us/step - accuracy: 0.9563 - loss: 0.1704 - val_accuracy: 0.9765 - val_loss: 0.1535
Epoch 22/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 422us/step - accuracy: 0.9721 - loss: 0.1531 - val_accuracy: 0.9805 - val_loss: 0.1428
Epoch 23/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 425us/step - accuracy: 0.9626 - loss: 0.1577 - val_accuracy: 0.9700 - val_loss: 0.1490
Epoch 24/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 425us/step - accuracy: 0.9655 - loss: 0.1532 - val_accuracy: 0.9650 - val_loss: 0.1433
Epoch 25/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 429us/step - accuracy: 0.9654 - loss: 0.1518 - val_accuracy: 0.9837 - val_loss: 0.1374
Epoch 26/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 427us/step - accuracy: 0.9678 - loss: 0.1468 - val_accuracy: 0.9360 - val_loss: 0.1696
Epoch 27/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 481us/step - accuracy: 0.9676 - loss: 0.1426 - val_accuracy: 0.9780 - val_loss: 0.1312
Epoch 28/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 426us/step - accuracy: 0.9698 - loss: 0.1408 - val_accuracy: 0.9835 - val_loss: 0.1291
Epoch 29/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 431us/step - accuracy: 0.9570 - loss: 0.1550 - val_accuracy: 0.9452 - val_loss: 0.1525
Epoch 30/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 437us/step - accuracy: 0.9655 - loss: 0.1439 - val_accuracy: 0.9542 - val_loss: 0.1460
157/157 ━━━━━━━━━━━━━━━━━━━━ 0s 361us/step - accuracy: 0.9842 - loss: 0.1281
Reloading Tuner from tuner_dir/untitled_project/tuner0.json
Epoch 1/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 553us/step - accuracy: 0.7355 - loss: 0.6629 - val_accuracy: 0.8020 - val_loss: 0.4406
Epoch 2/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 439us/step - accuracy: 0.8324 - loss: 0.4101 - val_accuracy: 0.8650 - val_loss: 0.3723
Epoch 3/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 445us/step - accuracy: 0.8556 - loss: 0.3553 - val_accuracy: 0.8660 - val_loss: 0.3519
Epoch 4/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 434us/step - accuracy: 0.8578 - loss: 0.3336 - val_accuracy: 0.8698 - val_loss: 0.3096
Epoch 5/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 436us/step - accuracy: 0.8695 - loss: 0.3113 - val_accuracy: 0.8790 - val_loss: 0.2949
Epoch 6/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 436us/step - accuracy: 0.8789 - loss: 0.2940 - val_accuracy: 0.8840 - val_loss: 0.2829
Epoch 7/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 432us/step - accuracy: 0.8865 - loss: 0.2808 - val_accuracy: 0.8957 - val_loss: 0.2689
Epoch 8/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 431us/step - accuracy: 0.8975 - loss: 0.2710 - val_accuracy: 0.9070 - val_loss: 0.2522
Epoch 9/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 443us/step - accuracy: 0.9107 - loss: 0.2526 - val_accuracy: 0.9022 - val_loss: 0.2471
Epoch 10/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 432us/step - accuracy: 0.9141 - loss: 0.2412 - val_accuracy: 0.9258 - val_loss: 0.2211
Epoch 11/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 694us/step - accuracy: 0.9321 - loss: 0.2209 - val_accuracy: 0.9423 - val_loss: 0.2063
Epoch 12/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 443us/step - accuracy: 0.9391 - loss: 0.2097 - val_accuracy: 0.9553 - val_loss: 0.1996
Epoch 13/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 511us/step - accuracy: 0.9483 - loss: 0.2015 - val_accuracy: 0.9532 - val_loss: 0.2078
Epoch 14/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 431us/step - accuracy: 0.9520 - loss: 0.1922 - val_accuracy: 0.9668 - val_loss: 0.1834
Epoch 15/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 441us/step - accuracy: 0.9543 - loss: 0.1839 - val_accuracy: 0.9675 - val_loss: 0.1691
Epoch 16/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 438us/step - accuracy: 0.9621 - loss: 0.1736 - val_accuracy: 0.9655 - val_loss: 0.1642
Epoch 17/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 433us/step - accuracy: 0.9633 - loss: 0.1733 - val_accuracy: 0.9715 - val_loss: 0.1567
Epoch 18/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 430us/step - accuracy: 0.9607 - loss: 0.1670 - val_accuracy: 0.9473 - val_loss: 0.1733
Epoch 19/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 452us/step - accuracy: 0.9635 - loss: 0.1644 - val_accuracy: 0.9812 - val_loss: 0.1497
Epoch 20/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 460us/step - accuracy: 0.9636 - loss: 0.1621 - val_accuracy: 0.9795 - val_loss: 0.1493
Epoch 21/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 486us/step - accuracy: 0.9673 - loss: 0.1529 - val_accuracy: 0.9787 - val_loss: 0.1403
Epoch 22/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 436us/step - accuracy: 0.9659 - loss: 0.1544 - val_accuracy: 0.9843 - val_loss: 0.1423
Epoch 23/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 431us/step - accuracy: 0.9661 - loss: 0.1530 - val_accuracy: 0.9703 - val_loss: 0.1373
Epoch 24/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 429us/step - accuracy: 0.9679 - loss: 0.1467 - val_accuracy: 0.9830 - val_loss: 0.1364
Epoch 25/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 431us/step - accuracy: 0.9666 - loss: 0.1482 - val_accuracy: 0.9635 - val_loss: 0.1571
Epoch 26/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 479us/step - accuracy: 0.9678 - loss: 0.1439 - val_accuracy: 0.9827 - val_loss: 0.1285
Epoch 27/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 426us/step - accuracy: 0.9694 - loss: 0.1386 - val_accuracy: 0.9718 - val_loss: 0.1293
Epoch 28/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 438us/step - accuracy: 0.9707 - loss: 0.1374 - val_accuracy: 0.9780 - val_loss: 0.1290
Epoch 29/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 434us/step - accuracy: 0.9732 - loss: 0.1351 - val_accuracy: 0.9500 - val_loss: 0.1477
Epoch 30/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 432us/step - accuracy: 0.9721 - loss: 0.1315 - val_accuracy: 0.9843 - val_loss: 0.1199
157/157 ━━━━━━━━━━━━━━━━━━━━ 0s 360us/step - accuracy: 0.9855 - loss: 0.1166
Reloading Tuner from tuner_dir/untitled_project/tuner0.json
Epoch 1/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 566us/step - accuracy: 0.7154 - loss: 0.6752 - val_accuracy: 0.8282 - val_loss: 0.4151
Epoch 2/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 433us/step - accuracy: 0.8390 - loss: 0.4039 - val_accuracy: 0.8635 - val_loss: 0.3664
Epoch 3/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 430us/step - accuracy: 0.8583 - loss: 0.3534 - val_accuracy: 0.8593 - val_loss: 0.3316
Epoch 4/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 437us/step - accuracy: 0.8631 - loss: 0.3290 - val_accuracy: 0.8618 - val_loss: 0.3164
Epoch 5/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 428us/step - accuracy: 0.8723 - loss: 0.3108 - val_accuracy: 0.8705 - val_loss: 0.3199
Epoch 6/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 430us/step - accuracy: 0.8719 - loss: 0.3056 - val_accuracy: 0.8733 - val_loss: 0.2954
Epoch 7/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 429us/step - accuracy: 0.8769 - loss: 0.2930 - val_accuracy: 0.8800 - val_loss: 0.2875
Epoch 8/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 427us/step - accuracy: 0.8843 - loss: 0.2842 - val_accuracy: 0.8885 - val_loss: 0.2709
Epoch 9/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 432us/step - accuracy: 0.8931 - loss: 0.2697 - val_accuracy: 0.9015 - val_loss: 0.2555
Epoch 10/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 501us/step - accuracy: 0.9041 - loss: 0.2542 - val_accuracy: 0.9143 - val_loss: 0.2560
Epoch 11/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 436us/step - accuracy: 0.9215 - loss: 0.2314 - val_accuracy: 0.8990 - val_loss: 0.2468
Epoch 12/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 429us/step - accuracy: 0.9305 - loss: 0.2237 - val_accuracy: 0.9488 - val_loss: 0.2106
Epoch 13/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 431us/step - accuracy: 0.9380 - loss: 0.2126 - val_accuracy: 0.9540 - val_loss: 0.2059
Epoch 14/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 427us/step - accuracy: 0.9464 - loss: 0.2021 - val_accuracy: 0.9500 - val_loss: 0.2038
Epoch 15/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 431us/step - accuracy: 0.9510 - loss: 0.1921 - val_accuracy: 0.9390 - val_loss: 0.1892
Epoch 16/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 431us/step - accuracy: 0.9549 - loss: 0.1817 - val_accuracy: 0.9503 - val_loss: 0.1779
Epoch 17/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 438us/step - accuracy: 0.9594 - loss: 0.1783 - val_accuracy: 0.9682 - val_loss: 0.1646
Epoch 18/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 431us/step - accuracy: 0.9578 - loss: 0.1730 - val_accuracy: 0.9732 - val_loss: 0.1592
Epoch 19/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 428us/step - accuracy: 0.9597 - loss: 0.1694 - val_accuracy: 0.9630 - val_loss: 0.1694
Epoch 20/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 431us/step - accuracy: 0.9669 - loss: 0.1588 - val_accuracy: 0.9417 - val_loss: 0.1778
Epoch 21/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 426us/step - accuracy: 0.9665 - loss: 0.1562 - val_accuracy: 0.9657 - val_loss: 0.1508
Epoch 22/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 433us/step - accuracy: 0.9685 - loss: 0.1538 - val_accuracy: 0.9778 - val_loss: 0.1429
Epoch 23/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 488us/step - accuracy: 0.9724 - loss: 0.1479 - val_accuracy: 0.9680 - val_loss: 0.1454
Epoch 24/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 425us/step - accuracy: 0.9685 - loss: 0.1453 - val_accuracy: 0.9503 - val_loss: 0.1571
Epoch 25/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 430us/step - accuracy: 0.9682 - loss: 0.1475 - val_accuracy: 0.9287 - val_loss: 0.1867
Epoch 26/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 429us/step - accuracy: 0.9657 - loss: 0.1454 - val_accuracy: 0.9862 - val_loss: 0.1311
Epoch 27/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 426us/step - accuracy: 0.9745 - loss: 0.1358 - val_accuracy: 0.9793 - val_loss: 0.1291
Epoch 28/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 426us/step - accuracy: 0.9665 - loss: 0.1423 - val_accuracy: 0.9597 - val_loss: 0.1416
Epoch 29/30

### Comparison

In [9]:
results.groupby('model').agg({'Accuracy':['mean','std']}).sort_values(by=('Accuracy', 'mean'),ascending=False)

                  Accuracy
                      mean       std
model
GradientBoostingC  0.98776  0.001108
Tensorflow         0.97664  0.007869

### Model hiperparameter tunning and model training

In [10]:
mdc = GridSearchCV(GradientBoostingClassifier(),
    param_grid={"n_estimators": np.linspace(50,200,10).astype('int'),  
                "max_depth": np.linspace(1,10,5).astype('int')},
    n_jobs=8) 
mdc.fit(X, y)
mdc.best_params_ # {'max_depth': 5, 'n_estimators': 100}

# Save the model
import joblib
joblib.dump(mdc.best_estimator_, 'gbc_best_model.pkl')
# Load the model
loaded_model = joblib.load('gbc_best_model.pkl')

In [11]:
tuner = RandomSearch(build_model, objective='val_accuracy', max_trials=10, executions_per_trial=1, directory='tuner_dir')
tuner.search(X, y, epochs=30, validation_split=0.2, batch_size=32)
best_hps = tuner.get_best_hyperparameters(num_trials=1)[0]

print(f"Best TensorFlow Model: units={best_hps.get('units')}, learning_rate={best_hps.get('learning_rate')}")

# Save the model
best_model.save('tf_best_model.keras')
# Load the model
loaded_model = keras.models.load_model('tf_best_model.keras')

Reloading Tuner from tuner_dir/untitled_project/tuner0.json
Best TensorFlow Model: units=128, learning_rate=0.001