## Skorch vs. TensorFlow: Comparación para Clasificación de Datos Tabulares
### 1. ¿Qué es Skorch?
Skorch es un wrapper que permite utilizar redes neuronales de PyTorch con una API similar a la de scikit-learn, lo que facilita la integración con pipelines y herramientas como GridSearchCV.


Se usa cuando queremos aprovechar la flexibilidad de PyTorch pero con la simplicidad de scikit-learn.
### 2. ¿Qué es TensorFlow?
TensorFlow es una librería de aprendizaje profundo desarrollada por Google, con herramientas como Keras, que simplifican la creación y ajuste de redes neuronales.


s más adecuado para modelos de producción, entrenamiento distribuido y optimización con aceleración por hardware (GPU/TPU).


### 3. Ajuste de Hiperparámetros
Para ambos frameworks, podemos ajustar:

* Arquitectura de la red: Número de capas, neuronas por capa.

* Funciones de activación: ReLU, Sigmoid, etc.

* Tasa de aprendizaje (learning_rate).

* Tamaño del batch (batch_size).

* Número de épocas (epochs).

* Optimizador: Adam, SGD, etc.


Para encontrar la mejor combinación, usaremos GridSearchCV con Skorch y Keras Tuner para TensorFlow.

In [ ]:
!pip install torch
!pip install skorch
!pip install keras-tuner

In [27]:
import numpy as np
import pandas as pd
import torch
import torch.nn as nn
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from sklearn.model_selection import train_test_split, GridSearchCV
from skorch import NeuralNetClassifier
from skorch.helper import SliceDataset
from skorch.callbacks import EarlyStopping
from skorch.callbacks import EpochScoring

In [6]:
# Carga del dataset de simulaciones
data=pd.read_csv('./data/C2018-13-Christmas-market/simulation_C2018-13-Christmas-market_tp2_ev0.0713.csv',index_col=0)
data.head(2)

,duration1,duration2,duration3,duration4,duration5,duration6,duration7,duration8,duration21,duration9,...,duration26,duration28,duration29,duration30,duration31,duration32,duration33,critical_path,baseline_duration,actual_duration
0,0,59,257.956695,10.093668,18.189347,266.724319,112.345085,128.122007,46.119746,179.073063,...,17.321310,9.933554,11.313659,10.880869,16.825025,7.786062,0,"[1, 2, 3, 4, 6, 13, 27, 28, 29, 31, 32, 33]",1107.6,1128.504156
1,0,59,277.539098,10.225146,16.415950,273.195967,115.535606,121.148158,48.234513,134.272704,...,16.494392,10.049567,10.605734,10.358704,18.822929,9.487006,0,"[1, 2, 3, 4, 6, 13, 27, 28, 29, 31, 32, 33]",1107.6,1186.873800

In [7]:
# Creo la columna delay y elimino baseline duration y actual duration
data['delay']=(data['actual_duration']>data['baseline_duration'])*1
data.drop(columns=['baseline_duration','actual_duration','critical_path'],inplace=True)
data.head(2)

,duration1,duration2,duration3,duration4,duration5,duration6,duration7,duration8,duration21,duration9,...,duration23,duration25,duration26,duration28,duration29,duration30,duration31,duration32,duration33,delay
0,0,59,257.956695,10.093668,18.189347,266.724319,112.345085,128.122007,46.119746,179.073063,...,8.301023,8.483037,17.321310,9.933554,11.313659,10.880869,16.825025,7.786062,0,1
1,0,59,277.539098,10.225146,16.415950,273.195967,115.535606,121.148158,48.234513,134.272704,...,7.211210,8.247698,16.494392,10.049567,10.605734,10.358704,18.822929,9.487006,0,1

In [9]:
# Split the dataset into features and class
X = data.drop(columns=['delay'])
y = data['delay']

# Se usa stratify=y en train_test_split para asegurar que la distribución de clases sea la misma en entrenamiento y prueba.
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

# Verificar la distribución de clases (me están saliendo accuracies de 1 xq sólo tenemos datos con retraso)
print("Unique labels in training:", np.unique(y_train, return_counts=True))
print("Unique labels in test:", np.unique(y_test, return_counts=True))

Unique labels in training: (array([0, 1]), array([212, 588]))
Unique labels in test: (array([0, 1]), array([ 53, 147]))

In [37]:
# ---- Modelo con Skorch ----
class SkorchNet(nn.Module):
    def __init__(self, input_dim=33, hidden_dim=64, output_dim=2):
        super(SkorchNet, self).__init__()
        self.fc1 = nn.Linear(input_dim, hidden_dim)
        self.bn1 = nn.BatchNorm1d(hidden_dim)  # Normalización (como hace TF)
        self.relu = nn.ReLU()
        #self.dropout = nn.Dropout(0.5)  # Agrega Dropout
        self.fc2 = nn.Linear(hidden_dim, output_dim)
        self.softmax = nn.Softmax(dim=1)

    def forward(self, X):
        X = self.fc1(X)
        X = self.relu(X)
        #X = self.dropout(X)  # Dropout aplicado aquí
        X = self.fc2(X)
        return self.softmax(X)

net = NeuralNetClassifier(
    SkorchNet,
    module__input_dim=33,
    module__hidden_dim=64,  # Valor por defecto, pero se tuneará en GridSearch
    module__output_dim=2,
    max_epochs=30,
    lr=0.001,
    optimizer=torch.optim.AdamW,
    optimizer__weight_decay=0.01,  # Regularización L2 penaliza los pesos grandes en la red neuronal para evitar el sobreajuste (overfitting)
    criterion=nn.CrossEntropyLoss,
    batch_size=32,
    iterator_train__shuffle=True,
    callbacks=[EarlyStopping(patience=5, load_best=True), EpochScoring('accuracy', on_train=True), EpochScoring('accuracy', on_train=False)]


)

# GridSearch para Skorch, ahora tunnea hidden_dim
params = {
    'lr': [0.01, 0.001, 0.0001, 0.00005],
    'batch_size': [8, 16, 32, 64],
    'module__hidden_dim': [32, 64, 128, 256]  # Ahora se ajusta hidden_dim
}

gs = GridSearchCV(net, params, scoring='accuracy', cv=5)
gs.fit(X_train.values.astype(np.float32), y_train.values)

print("Best Skorch Model:", gs.best_params_)
print("Best Skorch Accuracy:", gs.best_score_)


# Como detectar overfitting
#Si train_loss baja pero valid_loss sube, el modelo está memorizando los datos de entrenamiento y no generaliza bien.
#Si train_acc es mucho mayor que valid_acc, también es señal de sobreajuste.

  epoch    accuracy    train_loss    valid_acc    valid_loss     dur
-------  ----------  ------------  -----------  ------------  ------
      1      0.7344        0.5828       0.7344        0.5789  0.0349
      2      0.7344        0.5789       0.7344        0.5789  0.0292
      3      0.7344        0.5789       0.7344        0.5789  0.0264
      4      0.7344        0.5789       0.7344        0.5789  0.0250
      5      0.7344        0.5789       0.7344        0.5789  0.0248
Stopping since valid_loss has not improved in the last 5 epochs.
Restoring best model from epoch 1.
  epoch    accuracy    train_loss    valid_acc    valid_loss     dur
-------  ----------  ------------  -----------  ------------  ------
      1      0.2656        1.0476       0.2656        1.0476  0.0251
      2      0.2656        1.0476       0.2656        1.0476  0.0256
      3      0.2656        1.0476       0.2656        1.0476  0.0654
      4      0.2656        1.0476       0.2656        1.0476  0.0253
      5      0.2656        1.0476       0.2656        1.0476  0.0259
Stopping since valid_loss has not improved in the last 5 epochs.
Restoring best model from epoch 1.
  epoch    accuracy    train_loss    valid_acc    valid_loss     dur
-------  ----------  ------------  -----------  ------------  ------
      1      0.2656        1.0437       0.2656        1.0476  0.0241
      2      0.2656        1.0476       0.2656        1.0476  0.0242
      3      0.2656        1.0476       0.2656        1.0476  0.0249
      4      0.2656        1.0476       0.2656        1.0476  0.0248
      5      0.2656        1.0476       0.2656        1.0476  0.0246
Stopping since valid_loss has not improved in the last 5 epochs.
Restoring best model from epoch 1.
  epoch    accuracy    train_loss    valid_acc    valid_loss     dur
-------  ----------  ------------  -----------  ------------  ------
      1      0.2578        1.0476       0.2578        1.0554  0.0243
      2      0.2578        1.0476       0.2578        1.0554  0.0279
      3      0.2578        1.0476       0.2578        1.0554  0.0248
      4      0.2578        1.0476       0.2578        1.0554  0.0244
      5      0.2578        1.0476       0.2578        1.0554  0.0247
Stopping since valid_loss has not improved in the last 5 epochs.
Restoring best model from epoch 1.
  epoch    accuracy    train_loss    valid_acc    valid_loss     dur
-------  ----------  ------------  -----------  ------------  ------
      1      0.7422        0.8992       0.7422        0.5711  0.0237
      2      0.7422        0.5789       0.7422        0.5711  0.0251
      3      0.7422        0.5789       0.7422        0.5711  0.0249
      4      0.7422        0.5789       0.7422        0.5711  0.0247
      5      0.7422        0.5789       0.7422        0.5711  0.0245
Stopping since valid_loss has not improved in the last 5 epochs.
Restoring best model from epoch 1.
  epoch    accuracy    train_loss    valid_acc    valid_loss     dur
-------  ----------  ------------  -----------  ------------  ------
      1      0.7344        0.5789       0.7344        0.5789  0.0260
      2      0.7344        0.5789       0.7344        0.5789  0.0270
      3      0.7344        0.5789       0.7344        0.5789  0.0258
      4      0.7344        0.5789       0.7344        0.5789  0.0258
      5      0.7344        0.5789       0.7344        0.5789  0.0321
Stopping since valid_loss has not improved in the last 5 epochs.
Restoring best model from epoch 1.
  epoch    accuracy    train_loss    valid_acc    valid_loss     dur
-------  ----------  ------------  -----------  ------------  ------
      1      0.2656        1.0476       0.2656        1.0476  0.0251
      2      0.2656        1.0476       0.2656        1.0476  0.0264
      3      0.2656        1.0476       0.2656        1.0476  0.0258
      4      0.2656        1.0476       0.2656        1.0476  0.0259
      5      0.2656        1.0476       0.2656        1.0476  0.0265
Stopping since valid_loss has not improved in the last 5 epochs.
Restoring best model from epoch 1.
  epoch    accuracy    train_loss    valid_acc    valid_loss     dur
-------  ----------  ------------  -----------  ------------  ------
      1      0.7344        0.6922       0.7344        0.5789  0.0253
      2      0.7344        0.5789       0.7344        0.5789  0.0261
      3      0.7344        0.5789       0.7344        0.5789  0.0260
      4      0.7344        0.5789       0.7344        0.5789  0.0267
      5      0.7344        0.5789       0.7344        0.5789  0.0260
Stopping since valid_loss has not improved in the last 5 epochs.
Restoring best model from epoch 1.
  epoch    accuracy    train_loss    valid_acc    valid_loss     dur
-------  ----------  ------------  -----------  ------------  ------
      1      0.2578        1.0476       0.2578        1.0554  0.0254
      2      0.2578        1.0476       0.2578        1.0554  0.0257
      3      0.2578        1.0476       0.2578        1.0554  0.0257
      4      0.2578        1.0476       0.2578        1.0554  0.0260
      5      0.2578        1.0476       0.2578        1.0554  0.0255
Stopping since valid_loss has not improved in the last 5 epochs.
Restoring best model from epoch 1.
  epoch    accuracy    train_loss    valid_acc    valid_loss     dur
-------  ----------  ------------  -----------  ------------  ------
      1      0.7422        0.5805       0.7422        0.5711  0.0264
      2      0.7422        0.5789       0.7422        0.5711  0.0261
      3      0.7422        0.5789       0.7422        0.5711  0.0255
      4      0.7422        0.5789       0.7422        0.5711  0.0282
      5      0.7422        0.5789       0.7422        0.5711  0.0274
Stopping since valid_loss has not improved in the last 5 epochs.
Restoring best model from epoch 1.
  epoch    accuracy    train_loss    valid_acc    valid_loss     dur
-------  ----------  ------------  -----------  ------------  ------
      1      0.2656        1.0476       0.2656        1.0476  0.0263
      2      0.2656        1.0476       0.2656        1.0476  0.0273
      3      0.2656        1.0476       0.2656        1.0476  0.0272
      4      0.2656        1.0476       0.2656        1.0476  0.0268
      5      0.2656        1.0476       0.2656        1.0476  0.0268
Stopping since valid_loss has not improved in the last 5 epochs.
Restoring best model from epoch 1.
  epoch    accuracy    train_loss    valid_acc    valid_loss     dur
-------  ----------  ------------  -----------  ------------  ------
      1      0.7344        0.5789       0.7344        0.5789  0.0259
      2      0.7344        0.5789       0.7344        0.5789  0.0278
      3      0.7344        0.5789       0.7344        0.5789  0.0272
      4      0.7344        0.5789       0.7344        0.5789  0.0271
      5      0.7344        0.5789       0.7344        0.5789  0.0265
Stopping since valid_loss has not improved in the last 5 epochs.
Restoring best model from epoch 1.
  epoch    accuracy    train_loss    valid_acc    valid_loss     dur
-------  ----------  ------------  -----------  ------------  ------
      1      0.7344        0.5945       0.7344        0.5789  0.0265
      2      0.7344        0.5789       0.7344        0.5789  0.0274
      3      0.7344        0.5789       0.7344        0.5789  0.0272
      4      0.7344        0.5789       0.7344        0.5789  0.0313
      5      0.7344        0.5789       0.7344        0.5789  0.0271
Stopping since valid_loss has not improved in the last 5 epochs.
Restoring best model from epoch 1.
  epoch    accuracy    train_loss    valid_acc    valid_loss     dur
-------  ----------  ------------  -----------  ------------  ------
      1      0.7422        0.5905       0.7422        0.5711  0.0269
      2      0.7422        0.5789       0.7422        0.5711  0.0267
      3      0.7422        0.5789       0.7422        0.5711  0.0269
      4      0.7422        0.5789       0.7422        0.5711  0.0271
      5      0.7422        0.5789       0.7422        0.5711  0.0269
Stopping since valid_loss has not improved in the last 5 epochs.
Restoring best model from epoch 1.
  epoch    accuracy    train_loss    valid_acc    valid_loss     dur
-------  ----------  ------------  -----------  ------------  ------
      1      0.7422        0.5867       0.7422        0.5711  0.0269
      2      0.7422        0.5789       0.7422        0.5711  0.0270
      3      0.7422        0.5789       0.7422        0.5711  0.0266
      4      0.7422        0.5789       0.7422        0.5711  0.0275
      5      0.7422        0.5789       0.7422        0.5711  0.0271
Stopping since valid_loss has not improved in the last 5 epochs.
Restoring best model from epoch 1.
  epoch    accuracy    train_loss    valid_acc    valid_loss     dur
-------  ----------  ------------  -----------  ------------  ------
      1      0.2656        1.0476       0.2656        1.0476  0.0294
      2      0.2656        1.0476       0.2656        1.0476  0.0297
      3      0.2656        1.0431       0.2656        1.0476  0.0293
      4      0.2656        1.0476       0.2656        1.0476  0.0301
      5      0.2656        1.0476       0.2656        1.0476  0.0297
Stopping since valid_loss has not improved in the last 5 epochs.
Restoring best model from epoch 1.
  epoch    accuracy    train_loss    valid_acc    valid_loss     dur
-------  ----------  ------------  -----------  ------------  ------
      1      0.7344        0.7273       0.7344        0.5789  0.0290
      2      0.7344        0.5789       0.7344        0.5789  0.0290
      3      0.7344        0.5789       0.7344        0.5789  0.0293
      4      0.7344        0.5789       0.7344        0.5789  0.0296
      5      0.7344        0.5789       0.7344        0.5789  0.0294
Stopping since valid_loss has not improved in the last 5 epochs.
Restoring best model from epoch 1.
  epoch    accuracy    train_loss    valid_acc    valid_loss     dur
-------  ----------  ------------  -----------  ------------  ------
      1      0.2656        1.0476       0.2656        1.0476  0.0289
      2      0.2656        1.0476       0.2656        1.0476  0.0289
      3      0.2656        1.0476       0.2656        1.0476  0.0294
      4      0.2656        1.0476       0.2656        1.0476  0.0290
      5      0.2656        1.0476       0.2656        1.0476  0.0301
Stopping since valid_loss has not improved in the last 5 epochs.
Restoring best model from epoch 1.
  epoch    accuracy    train_loss    valid_acc    valid_loss     dur
-------  ----------  ------------  -----------  ------------  ------
      1      0.7422        0.5789       0.7422        0.5711  0.0300
      2      0.7422        0.5789       0.7422        0.5711  0.0298
      3      0.7422        0.5789       0.7422        0.5711  0.0294
      4      0.7422        0.5789       0.7422        0.5711  0.0291
      5      0.7422        0.5789       0.7422        0.5711  0.0294
Stopping since valid_loss has not improved in the last 5 epochs.
Restoring best model from epoch 1.
  epoch    accuracy    train_loss    valid_acc    valid_loss     dur
-------  ----------  ------------  -----------  ------------  ------
      1      0.2578        1.0359       0.2578        1.0554  0.0286
      2      0.2578        1.0476       0.2578        1.0554  0.0288
      3      0.2578        1.0476       0.2578        1.0554  0.0285
      4      0.2578        1.0476       0.2578        1.0554  0.0284
      5      0.2578        1.0476       0.2578        1.0554  0.0285
Stopping since valid_loss has not improved in the last 5 epochs.
Restoring best model from epoch 1.
  epoch    accuracy    train_loss    valid_acc    valid_loss     dur
-------  ----------  ------------  -----------  ------------  ------
      1      0.7344        0.5789       0.7344        0.5789  0.0237
      2      0.7344        0.5789       0.7344        0.5789  0.0249
      3      0.7344        0.5789       0.7344        0.5789  0.0244
      4      0.7344        0.5789       0.7344        0.5789  0.0243
      5      0.7344        0.5789       0.7344        0.5789  0.0244
Stopping since valid_loss has not improved in the last 5 epochs.
Restoring best model from epoch 1.
  epoch    accuracy    train_loss    valid_acc    valid_loss     dur
-------  ----------  ------------  -----------  ------------  ------
      1      0.7344        0.5802       0.7344        0.5789  0.0237
      2      0.7344        0.5789       0.7344        0.5789  0.0247
      3      0.7344        0.5789       0.7344        0.5789  0.0248
      4      0.7344        0.5789       0.7344        0.5789  0.0243
      5      0.7344        0.5789       0.7344        0.5789  0.0245
Stopping since valid_loss has not improved in the last 5 epochs.
Restoring best model from epoch 1.
  epoch    accuracy    train_loss    valid_acc    valid_loss     dur
-------  ----------  ------------  -----------  ------------  ------
      1      0.7344        0.5789       0.7344        0.5789  0.0242
      2      0.7344        0.5789       0.7344        0.5789  0.0240
      3      0.7344        0.5789       0.7344        0.5789  0.0243
      4      0.7344        0.5789       0.7344        0.5789  0.0243
      5      0.7344        0.5789       0.7344        0.5789  0.0248
Stopping since valid_loss has not improved in the last 5 epochs.
Restoring best model from epoch 1.
  epoch    accuracy    train_loss    valid_acc    valid_loss     dur
-------  ----------  ------------  -----------  ------------  ------
      1      0.7422        0.5793       0.7422        0.5710  0.0241
      2      0.7422        0.5790       0.7422        0.5711  0.0245
      3      0.7188        0.5816       0.7188        0.5884  0.0242
      4      0.7422        0.5782       0.7422        0.5711  0.0246
      5      0.7422        0.5789       0.7422        0.5711  0.0239
Stopping since valid_loss has not improved in the last 5 epochs.
Restoring best model from epoch 1.
  epoch    accuracy    train_loss    valid_acc    valid_loss     dur
-------  ----------  ------------  -----------  ------------  ------
      1      0.7422        0.5798       0.7422        0.5711  0.0237
      2      0.7422        0.5789       0.7422        0.5711  0.0245
      3      0.7422        0.5789       0.7422        0.5711  0.0246
      4      0.7422        0.5789       0.7422        0.5711  0.0243
      5      0.7422        0.5789       0.7422        0.5711  0.0242
Stopping since valid_loss has not improved in the last 5 epochs.
Restoring best model from epoch 1.
  epoch    accuracy    train_loss    valid_acc    valid_loss     dur
-------  ----------  ------------  -----------  ------------  ------
      1      0.2656        1.0477       0.2656        1.0476  0.0259
      2      0.2656        1.0476       0.2656        1.0476  0.0272
      3      0.2656        1.0476       0.2656        1.0476  0.0269
      4      0.2656        1.0476       0.2656        1.0476  0.0279
      5      0.2656        1.0476       0.2656        1.0476  0.0341
Stopping since valid_loss has not improved in the last 5 epochs.
Restoring best model from epoch 1.
  epoch    accuracy    train_loss    valid_acc    valid_loss     dur
-------  ----------  ------------  -----------  ------------  ------
      1      0.2656        1.0476       0.2656        1.0476  0.0271
      2      0.2656        1.0476       0.2656        1.0476  0.0267
      3      0.2656        1.0476       0.2656        1.0476  0.0277
      4      0.2656        1.0476       0.2656        1.0476  0.0274
      5      0.2656        1.0476       0.2656        1.0476  0.0274
Stopping since valid_loss has not improved in the last 5 epochs.
Restoring best model from epoch 1.
  epoch    accuracy    train_loss    valid_acc    valid_loss     dur
-------  ----------  ------------  -----------  ------------  ------
      1      0.2656        1.0476       0.2656        1.0476  0.0259
      2      0.2656        1.0476       0.2656        1.0476  0.0263
      3      0.2656        1.0476       0.2656        1.0476  0.0255
      4      0.2656        1.0476       0.2656        1.0476  0.0266
      5      0.2656        1.0476       0.2656        1.0476  0.0260
Stopping since valid_loss has not improved in the last 5 epochs.
Restoring best model from epoch 1.
  epoch    accuracy    train_loss    valid_acc    valid_loss     dur
-------  ----------  ------------  -----------  ------------  ------
      1      0.7422        0.5789       0.7422        0.5711  0.0253
      2      0.7422        0.5789       0.7422        0.5711  0.0266
      3      0.7422        0.5789       0.7422        0.5711  0.0262
      4      0.7422        0.5789       0.7422        0.5711  0.0263
      5      0.7422        0.5789       0.7422        0.5711  0.0259
Stopping since valid_loss has not improved in the last 5 epochs.
Restoring best model from epoch 1.
  epoch    accuracy    train_loss    valid_acc    valid_loss     dur
-------  ----------  ------------  -----------  ------------  ------
      1      0.2578        1.0476       0.2578        1.0554  0.0251
      2      0.2578        1.0476       0.2578        1.0554  0.0263
      3      0.2578        1.0476       0.2578        1.0554  0.0262
      4      0.2578        1.0476       0.2578        1.0554  0.0260
      5      0.2578        1.0476       0.2578        1.0554  0.0257
Stopping since valid_loss has not improved in the last 5 epochs.
Restoring best model from epoch 1.
  epoch    accuracy    train_loss    valid_acc    valid_loss     dur
-------  ----------  ------------  -----------  ------------  ------
      1      0.7344        0.5789       0.7344        0.5789  0.0261
      2      0.7344        0.5789       0.7344        0.5789  0.0273
      3      0.7344        0.5789       0.7344        0.5789  0.0273
      4      0.7344        0.5789       0.7344        0.5789  0.0268
      5      0.7344        0.5789       0.7344        0.5789  0.0267
Stopping since valid_loss has not improved in the last 5 epochs.
Restoring best model from epoch 1.
  epoch    accuracy    train_loss    valid_acc    valid_loss     dur
-------  ----------  ------------  -----------  ------------  ------
      1      0.2656        1.0476       0.2656        1.0476  0.0261
      2      0.2656        1.0476       0.2656        1.0476  0.0269
      3      0.2656        1.0476       0.2656        1.0476  0.0266
      4      0.2656        1.0476       0.2656        1.0476  0.0265
      5      0.2656        1.0476       0.2656        1.0476  0.0265
Stopping since valid_loss has not improved in the last 5 epochs.
Restoring best model from epoch 1.
  epoch    accuracy    train_loss    valid_acc    valid_loss     dur
-------  ----------  ------------  -----------  ------------  ------
      1      0.7344        0.5789       0.7344        0.5789  0.0264
      2      0.7344        0.5789       0.7344        0.5789  0.0317
      3      0.7344        0.5789       0.7344        0.5789  0.0268
      4      0.7344        0.5789       0.7344        0.5789  0.0272
      5      0.7344        0.5789       0.7344        0.5789  0.0267
Stopping since valid_loss has not improved in the last 5 epochs.
Restoring best model from epoch 1.
  epoch    accuracy    train_loss    valid_acc    valid_loss     dur
-------  ----------  ------------  -----------  ------------  ------
      1      0.2578        1.0485       0.2578        1.0554  0.0264
      2      0.2578        1.0476       0.2578        1.0554  0.0272
      3      0.2578        1.0476       0.2578        1.0554  0.0267
      4      0.2578        1.0476       0.2578        1.0554  0.0270
      5      0.2578        1.0476       0.2578        1.0554  0.0267
Stopping since valid_loss has not improved in the last 5 epochs.
Restoring best model from epoch 1.
  epoch    accuracy    train_loss    valid_acc    valid_loss     dur
-------  ----------  ------------  -----------  ------------  ------

In [38]:
# ---- Modelo con TensorFlow ----
def build_model(hp):
    model = keras.Sequential([
        layers.Dense(hp.Int('units', min_value=32, max_value=128, step=32), activation='relu', kernel_regularizer=tf.keras.regularizers.l2(0.01)),
        #layers.Dropout(0.5),  # Agrega Dropout
        layers.Dense(2, activation='softmax')
    ])
    model.compile(optimizer=keras.optimizers.Adam(hp.Choice('learning_rate', [0.01, 0.001, 0.0001])),
                  loss='sparse_categorical_crossentropy',
                  metrics=['accuracy'])
    return model

from kerastuner.tuners import RandomSearch
tuner = RandomSearch(build_model, objective='val_accuracy', max_trials=10, executions_per_trial=1, directory='tuner_dir')

tuner.search(X_train, y_train, epochs=30, validation_split=0.2, batch_size=32)
best_hps = tuner.get_best_hyperparameters(num_trials=1)[0]

print(f"Best TensorFlow Model: units={best_hps.get('units')}, learning_rate={best_hps.get('learning_rate')}")

# Evaluación final con los mejores hiperparámetros
best_model = tuner.hypermodel.build(best_hps)
best_model.fit(X_train, y_train, epochs=30, batch_size=32, validation_split=0.2, callbacks=[tf.keras.callbacks.EarlyStopping(patience=5, restore_best_weights=True)])
test_loss, test_acc = best_model.evaluate(X_test, y_test)

print("Best TensorFlow Accuracy:", test_acc)

Reloading Tuner from tuner_dir/untitled_project/tuner0.json
Best TensorFlow Model: units=64, learning_rate=0.001
Epoch 1/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6506 - loss: 4.1890 - val_accuracy: 0.4688 - val_loss: 4.8741
Epoch 2/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5709 - loss: 4.2019 - val_accuracy: 0.6438 - val_loss: 2.8495
Epoch 3/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6027 - loss: 3.2529 - val_accuracy: 0.5562 - val_loss: 2.4883
Epoch 4/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6398 - loss: 2.2886 - val_accuracy: 0.7188 - val_loss: 2.7145
Epoch 5/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6828 - loss: 2.5324 - val_accuracy: 0.5750 - val_loss: 2.7472
Epoch 6/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6202 - loss: 2.5750 - val_accuracy: 0.5875 - val_loss: 2.0858
Epoch 7/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6843 - loss: 1.8076 - val_accuracy: 0.7125 - val_loss: 1.5491
Epoch 8/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6965 - loss: 1.7691 - val_accuracy: 0.7188 - val_loss: 1.5070
Epoch 9/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7173 - loss: 1.5648 - val_accuracy: 0.7500 - val_loss: 1.2566
Epoch 10/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7037 - loss: 1.6180 - val_accuracy: 0.7125 - val_loss: 1.2165
Epoch 11/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6722 - loss: 1.6996 - val_accuracy: 0.4625 - val_loss: 3.0351
Epoch 12/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6798 - loss: 1.8297 - val_accuracy: 0.7625 - val_loss: 1.2119
Epoch 13/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7475 - loss: 1.4934 - val_accuracy: 0.7750 - val_loss: 0.9215
Epoch 14/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7690 - loss: 1.0986 - val_accuracy: 0.7875 - val_loss: 0.9832
Epoch 15/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7804 - loss: 0.9639 - val_accuracy: 0.8000 - val_loss: 0.8574
Epoch 16/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7987 - loss: 0.8793 - val_accuracy: 0.8062 - val_loss: 0.7491
Epoch 17/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7734 - loss: 0.9454 - val_accuracy: 0.7750 - val_loss: 1.0625
Epoch 18/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8063 - loss: 1.1306 - val_accuracy: 0.7937 - val_loss: 0.8456
Epoch 19/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7725 - loss: 1.0306 - val_accuracy: 0.7812 - val_loss: 1.1701
Epoch 20/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7795 - loss: 1.1786 - val_accuracy: 0.8562 - val_loss: 0.6748
Epoch 21/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7725 - loss: 1.2456 - val_accuracy: 0.7375 - val_loss: 1.0859
Epoch 22/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7734 - loss: 1.0018 - val_accuracy: 0.8500 - val_loss: 0.6888
Epoch 23/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8482 - loss: 0.7224 - val_accuracy: 0.8438 - val_loss: 0.7017
Epoch 24/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8581 - loss: 0.6558 - val_accuracy: 0.8750 - val_loss: 0.5926
Epoch 25/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8397 - loss: 0.6179 - val_accuracy: 0.8562 - val_loss: 0.5465
Epoch 26/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8358 - loss: 0.6606 - val_accuracy: 0.8500 - val_loss: 0.6407
Epoch 27/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8221 - loss: 0.8073 - val_accuracy: 0.7312 - val_loss: 0.9348
Epoch 28/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7767 - loss: 0.9282 - val_accuracy: 0.8375 - val_loss: 0.7239
Epoch 29/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8679 - loss: 0.6129 - val_accuracy: 0.9000 - val_loss: 0.4843
Epoch 30/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8602 - loss: 0.5984 - val_accuracy: 0.8687 - val_loss: 0.4842
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8610 - loss: 0.5302
Best TensorFlow Accuracy: 0.8849999904632568